
version: '3'
services:
  app:
    image: hastic/hastic:latest
    network_mode: host
    environment:
      HASTIC_PORT: "4347"
      HASTIC_PROMETHEUS__URL: "http://demo.robustperception.io:9090"
      HASTIC_PROMETHEUS__QUERY: "rate(go_memstats_alloc_bytes_total[1m])"
    ports:
      - "4347:4347"
